
import './globals.css';
import '../assets/stylesheets/presets.css';

import { NotoSans } from "@/assets/fontsconfigure";

export const metadata = {
  title: "Frontend Extension Manager",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={NotoSans.className}
      >
        {children}
      </body>
    </html>
  );
}
